[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"
  publish = "public"

[[redirects]]
  from = "/api/submissions"
  to = "/.netlify/functions/submissions"
  status = 200
  force = true

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200
  force = true

[[redirects]]
  from = "/api/roster"
  to = "/.netlify/functions/roster"
  status = 200
  force = true

[[edge_functions]]
  path = "/api/media"
  function = "media"

[[edge_functions]]
  path = "/api/upload"
  function = "upload"
